### ISSUE TITLE
Make changes to README.md if needed

### ISSUE THREAD

**Issue by souvikrajsingh** [souvikrajsingh/StudentHelp#2]
make the README.md file more easy to understand and readable if you can in some way, be it by adding emojis pictures or videos to help the folks doing it for the first time

**Comment by pantbibek21** [comment]
Hello sir, I would like to work on this. I could make README.md a little better. Please, assign this issue to me.

**Comment by souvikrajsingh** [comment]
i have assinged you the issue @pantbibek21 !

**Comment by pantbibek21** [comment]
@souvikrajsingh, thanks. By the way, we could add a hacktoberfest 2022 official image at the top of our readme.md file but for that rather than being subjected to copyright issues of the image and we could add a folder named Images and keep the image there. And use it from there. What do you think sir? Shall I begin?

**Comment by souvikrajsingh** [comment]
good idea bibek! get started 👌🏽

**Comment by siddarthpai** [comment]
Hello sir, I would like to work on this, thank you

**Comment by souvikrajsingh** [comment]
Assigned you this issue! Please get started
